env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
rules:
  {
    'import/extensions': ['.js', '.jsx', '.json', '.ts', '.tsx'],
    'react/jsx-filename-extension': ['error', { 'extensions': ['.jsx', '.tsx'] }],
    'react/function-component-definition': ['error', { 'namedComponents': 'arrow-function' }],
    'import/no-extraneous-dependencies': 'off',
    'react/jsx-uses-react': 'off',
    'react/react-in-jsx-scope': 'off',
    'import/prefer-default-export': 'off',
  }
