name: cache_cargo
description: caching .cargo directory
inputs:
  dir:
    default: ''
    required: false
runs:
  using: composite
  steps:
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ${{ inputs.dir }}/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
