name: build_wasm_pack
description: building by wasm-pack
runs:
  using: composite
  steps:
    - name: Set rust toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install tools
      run: cargo install --force cargo-make wasm-pack
      working-directory: wasm/bevy-app
    - name: Build by wasm-pack
      run: cargo make build
      working-directory: wasm/bevy-app
