[package]
name = "bevy-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib", "rlib"]
