name: build_rust_and_upload
description: building by wasm-pack and upload artifact
inputs:
  dir:
    required: true
runs:
  using: composite
  steps:
    - name: Set rust toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install tools
      run: cargo install --force cargo-make wasm-pack
      shell: bash
      working-directory: ${{ github.event.input.dir }}
    - name: Build by wasm-pack
      run: cargo make build
      shell: bash
      working-directory: ${{ github.event.input.dir }}
    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: bevy-app-dist
        path: ${{ github.event.input.dir }}/dist
        retention-days: 3
