name: build_rust_and_upload
description: building by wasm-pack and upload artifact
defaults:
  run:
    shell: bash
    working-directory: wasm/bevy-app
runs:
  using: composite
  steps:
    - name: Set rust toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install tools
      run: cargo install --force cargo-make wasm-pack
    - name: Build by wasm-pack
      run: cargo make build
    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: bevy-app-dist
        path: dist
