on: push
  
jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache_cargo
      - uses: ./.github/actions/build_wasm_pack
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: bevy-app-dist
          path: wasm/bevy-app/dist
  build-js:
    needs: build-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: bevy-app-dist
          path: wasm/bevy-app/dist
      - uses: ./.github/actions/build_vite
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build-js
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
