on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache_cargo
      - name: Set Toolchain
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: install tools
        run: cargo install cargo-make wasm-pack
        working-directory: wasm/bevy-app
      - name: echo
        run: cargo make echo
        working-directory: wasm/bevy-app
      - name: build
        run: cargo make build
        working-directory: wasm/bevy-app
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
